create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
create table category (id integer not null auto_increment, description varchar(255), name varchar(255), rating integer, url varchar(255), primary key (id)) engine=InnoDB;
INSERT INTO category(name, rating, description, url) VALUES ('First category', 5, 'A simple category', 'https://production.autoforce.com/uploads/version/profile_image/7009/comprar-gli_59ebc43f05.png');
